// import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         working
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.js</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//           <div className={styles.thirteen}>
//             <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             />
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }


import Link from 'next/link';
import React, { useEffect, useState } from 'react';
import Navbar from '../components/Navbar';

// const getData=(username)=>{
//   return fetch(`https://api.github.com/search/repositories?q=user:${username}+fork:true&sort=updated&per_page=10&type=Repositories`)
//   .then((res)=>res.json())
// }

const Index = ({data}) => {


// const [data,setdata]=useState([])


// useEffect(()=>{
//     getData(username).then((res)=>setdata(res.items))
// },[])

console.log(data)
  return (
       <>
       <Navbar
        
       />
    <div style={{
      display:"grid",gridTemplateColumns:"30% 70%",height:"881px",marginTop:"21px"}} >
        
       <div style={{display:"grid",gridTemplateRows:"42% 23% 40%",height:"750px"
      }} >

       <div style={{boxShadow: "rgba(0, 0, 0, 0.24) 0px 3px 8px", display:"grid" , gridTemplateRows:"31% 70%" }} > 
         <div style={{textAlign:"center"}} >
         <Link href={"https://github.com/kallol0011"} > <img src={data[0].owner.avatar_url} alt="user" style={{height:"92px",marginTop:"9px",
           borderRadius:"51%"
        }} /></Link>
        <Link style={{textDecoration:"none",color:"black"}} href={"https://github.com/kallol0011"}><h2 style={{textDecoration:"none",marginBottom:"0px",marginTop:"1px"}} >Kallol Sarkar</h2></Link>
          <Link style={{textDecoration:"none",color:"black"}} href={"https://github.com/kallol0011"} ><h3 style={{textDecoration:"none",marginBottom:"0px",marginTop:"1px",color:'grey'}} > @ {data[0].owner.login} </h3></Link>
          <h4 style={{color:'grey'}} >Full-stack Developer | FOSS | JavaScript | Typescript | NodeJS | Deno | ReactJS | HTML | CSS | Chakra-UI | MUI</h4>
         </div>
         <div style={{marginLeft:"28%",marginTop:"178px"}}  >
           <Link href={"http://ritesh-portfolio.s3-website.ap-south-1.amazonaws.com/resume.pdf"} > <button style={{backgroundColor:"royalblue"
          ,cursor:"pointer" ,paddingLeft:"18px",paddingRight:"18px",paddingTop:"7px",paddingBottom:"7px",color:"white",border:"none"
          }} >Resume</button></Link>
            <Link href={"https://github.com/kallol0011"} ><button style={{marginLeft:"18px",backgroundColor:"royalblue",color:"white"
           ,cursor:"pointer"  ,paddingLeft:"18px",paddingRight:"18px",paddingTop:"7px",paddingBottom:"7px",border:"none"
          }} >Follow</button>
            </Link>
         </div>
          
       </div>

       <div style={{marginTop:"21px",boxShadow: "rgba(0, 0, 0, 0.24) 0px 3px 8px"}}  >
      
        <br/>
        <br/>
        <button style={{marginLeft:"7px",marginRight:"7px"}} >TYPESCRIPT</button>
        <button style={{marginLeft:"7px",marginRight:"7px"}} >REACT.JS</button>
        <button style={{marginLeft:"7px",marginRight:"7px"}} >NODE.JS</button>
        <button style={{marginLeft:"7px",marginRight:"7px"}} >DENO</button>
        <button style={{marginLeft:"7px",marginRight:"7px"}} >MONGODB</button>
        <button style={{marginLeft:"7px",marginRight:"7px"}} >POSTGRE
        SQL</button>
        <button style={{marginLeft:"7px",marginRight:"7px"}} >GIT</button>
        <button style={{marginLeft:"7px",marginRight:"7px"}} >REACT
        NATIVE</button>
        <button style={{marginLeft:"7px",marginRight:"7px"}} >CHAKRA-UI</button>
        <button style={{marginLeft:"7px",marginRight:"7px"}} >CSS</button>
        <button style={{marginLeft:"7px",marginRight:"7px"}} >ANTD</button>
        <button style={{marginLeft:"7px",marginRight:"7px"}} >TAILWIND</button>
        <button style={{marginLeft:"7px",marginRight:"7px"}} >MUI</button>


       </div>

       <div style={{marginTop:"21px",boxShadow: "rgba(0, 0, 0, 0.24) 0px 3px 8px"}} >



       <div style={{marginLeft:"16px",marginBottom:"21px",marginTop:"11px"}} >
        
        <h4 style={{marginTop:"7px",marginBottom:"0px"}} >
        <span style={{marginRight:"6px"}} >1</span>
        SDE-3 at Masai School
        </h4>
        <p style={{marginTop:"0px",marginBottom:"0px"}} >
        October 2021 - Present
        </p>
       </div>

       <div style={{marginLeft:"16px",marginBottom:"21px"}} >
        
        <h4 style={{marginTop:"7px",marginBottom:"0px"}} >
        <span style={{marginRight:"6px"}} >2</span>
        Senior Software Engineer at Swiggy

        </h4>
        <p style={{marginTop:"0px",marginBottom:"0px"}} >
        November 2020 - September 2021
        </p>
       </div>

       <div style={{marginLeft:"16px",marginBottom:"21px"}} >
        
        <h4 style={{marginTop:"11px",marginBottom:"0px"}} >
        <span style={{marginRight:"6px"}} >3</span>
        Senior Software Engineer at Globant

        </h4>
        <p style={{marginTop:"0px",marginBottom:"0px"}} >
        September 2019 - November 2020
        </p>
       </div>

       <div style={{marginLeft:"16px",marginBottom:"11px"}} >
        
        <h4 style={{marginTop:"7px",marginBottom:"0px"}} >
        <span style={{marginRight:"6px"}} >4</span>
        Software Engineer at Confluxsys


        </h4>
        <p style={{marginTop:"0px",marginBottom:"0px"}} >
        June 2017 - September 2019
        </p>
       </div>

       </div>

       </div>


       {/* <div style={{border:"1px solid blue"}} >
        <h1>PROJECTS</h1>
       {
        data.map((el)=>(
          <div key={el.id} >
              <h2>{el.name}</h2>
              <h2>{el.stargazers_count}</h2>
              <h2>{el.forks_count}</h2>
              <h2>{el.language}</h2>
              
              <br/>
              <br/>
          </div>
        ))
       }
       </div> */}



         
<div style={{display:"grid", gridTemplateColumns:"50% 50%"}} >
        
        {
         data.map((el)=>(
           <div key={el.id} style={{
             
            boxShadow: "rgba(0, 0, 0, 0.16) 0px 1px 4px",backgroundColor:"white",display:"grid",gridTemplateColumns:"72% 28%",marginLeft:"21px"}} >
             <div style={{marginLeft:"11px"}} >
             <h2  >
                 <img src="https://img.freepik.com/free-icon/folder-gross-symbol-interface_318-53764.jpg?size=338&ext=jpg" style={{width:"27px"}} />
                 {el.name}</h2>
               <h2>
             <img src="https://img.freepik.com/free-icon/bookmarks_318-118638.jpg?size=338&ext=jpg" style={{width:"27px",marginLeft:"18px"}} />
                 {el.stargazers_count}
                 <span style={{marginLeft:"18%"}} >
                     <img src="https://img.freepik.com/free-icon/cloud-computing_318-925009.jpg?size=338&ext=jpg" style={{width:"27px"}} />
                     {el.forks_count}</span>
                 </h2>
               
 
             </div>
               
               <div>
 
               <h2>
                 <img src="https://img.freepik.com/free-icon/circle_318-891198.jpg?size=338&ext=jpg" alt="language logo" style={{width:"12px",marginRight:"11px"}} />
                 {el.language}</h2>
               </div>
               
               <br/>
               <br/>
           </div>
         ))
        }
        </div>



    </div>
    </>
  );
};

export default Index;




export async function getServerSideProps(){
  
  let username="kallol0011"
  // let username="riteshf"
  

  let res=await fetch(`https://api.github.com/search/repositories?q=user:${username}+fork:true&sort=updated&per_page=10&type=Repositories`)
  
  let d=await res.json()
  let d2=d.items
  return {
    props:{
      data:d2
    }
  }


}
 



